### ISSUE TITLE
JOGL issue, class not found? I don't know anything about Java

### ISSUE THREAD

**Issue by Moonfanz** [battlecatsultimate/BCU-java-PC#103]
java.lang.Exception: com/jogamp/opengl/GLProfile in main
	at main.MainBCU.noticeErr(MainBCU.java:395)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
Caused by: java.lang.NoClassDefFoundError: com/jogamp/opengl/GLProfile
	at jogl.GLStatic.<clinit>(GLStatic.java:19)
	at jogl.util.AmbImage.check(AmbImage.java:175)
	at jogl.util.AmbImage.getWidth(AmbImage.java:83)
	at common.system.VImg.load(VImg.java:96)
	at common.system.VImg.check(VImg.java:41)
	at common.system.VImg.getImg(VImg.java:45)
	at common.util.Res.readBattle(Res.java:280)
	at common.util.Res.readData(Res.java:133)
	at common.pack.PackData$DefPack.load(PackData.java:62)
	at main.MainBCU$AdminContext.initProfile(MainBCU.java:103)
	at main.MainBCU.main(MainBCU.java:371)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLProfile
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
com/jogamp/opengl/GLProfile in main
version: 0-5-2-15

**Comment by MandarinSmell** [comment]
You have to download BCU-Initializer first, then update it to the latest version

**Comment by Moonfanz** [comment]
will it override my existed data? it said "move to a new, empty folder", so what should i do ? back up my data?

**Comment by MandarinSmell** [comment]
Are you using this for first time?

**Comment by MandarinSmell** [comment]
Closing issue due to discontinued discussion
