### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Currypan1229** [battlecatsultimate/BCU-java-PC#81]
Release "BCU 0-5-1-0"

java.lang.NoClassDefFoundError: com/google/gson/JsonElement
        at common.pack.PackData.<init>(PackData.java:411)
        at common.pack.PackData$DefPack.<init>(PackData.java:51)
        at common.pack.UserProfile.<init>(UserProfile.java:323)
        at common.pack.UserProfile.profile(UserProfile.java:234)
        at main.MainBCU.main(MainBCU.java:301)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 5 more

Please add gson library
https://jar-download.com/artifacts/com.google.code.gson

**Comment by MandarinSmell** [comment]
You have to run BCU-Initializer first. We made it run by using external folder to reduce jar file size
