### ISSUE TITLE
Unit Import GUI Error

### ISSUE THREAD

**Issue by nicermak** [battlecatsultimate/BCU-java-PC#91]
When i finished import unit data,
the GUI is messed up,
and a pop-up windows is popped up.
"null in AWT-EventQueue-0"

**Comment by MandarinSmell** [comment]
Go to `logs` folder in BCU folder and upload the latest .log file (or contents of it if github doesn't allow)

**Comment by nicermak** [comment]
java.lang.NullPointerException
	at common.battle.data.PCoin.update(PCoin.java:97)
	at page.info.edit.FormEditPage.setData(FormEditPage.java:239)
	at page.info.edit.EntityEditPage.renew(EntityEditPage.java:321)
	at page.MainFrame.FchangePanel(MainFrame.java:217)
	at page.MainFrame.changePanel(MainFrame.java:34)
	at page.Page.changePanel(Page.java:128)
	at page.info.filter.UnitFindPage.lambda$0(UnitFindPage.java:96)
	at page.info.filter.UnitFindPage$$Lambda$336/669761413.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
null in AWT-EventQueue-0

**Comment by MandarinSmell** [comment]
We will try to solve it, avoid using feature, or don't import stat of that unit specifically

**Comment by Anemia88** [comment]
> 0x76b6eaff02bfd661d7db294b0cf5e90ee9266c3d

**Comment by nicermak** [comment]
Thank you so much!
